# Generated by Django 4.2 on 2023-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.CharField(default='na1', max_length=60),
        ),
    ]
